apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: app
data:
  DATABASE_HOST: postgres
  DATABASE_NAME: app
  DATABASE_USER: app
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_DEBUG: "false"

