from django.db import models
from django.conf import settings
from dicom_manager.models import DicomFile
import uuid


class Annotation(models.Model):
    """Model for storing annotations on DICOM images"""
    
    ANNOTATION_TYPES = (
        ("rectangle", "Rectangle/Bounding Box"),
        ("ellipse", "Ellipse"),
        ("polygon", "Polygon"),
        ("line", "Line"),
        ("point", "Point"),
        ("freehand", "Freehand"),
    )
    
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='annotations',
        help_text="User who created this annotation"
    )
    
    dicom_file = models.ForeignKey(
        DicomFile,
        on_delete=models.CASCADE,
        related_name='annotations',
        help_text="DICOM file this annotation belongs to"
    )
    
    annotation_type = models.CharField(
        max_length=20,
        choices=ANNOTATION_TYPES,
        default="rectangle",
        help_text="Type of annotation tool used"
    )
    
    label = models.CharField(
        max_length=100,
        help_text="Label/description for the annotation (e.g., 'fracture', 'tumor')"
    )
    
    coordinates = models.JSONField(
        help_text="Coordinates of the annotation (format depends on annotation_type)"
    )
    
    color = models.CharField(
        max_length=7,
        default="#FF0000",
        help_text="Color of the annotation in hex format"
    )
    
    notes = models.TextField(
        blank=True,
        null=True,
        help_text="Additional notes or comments about the annotation"
    )
    
    confidence_score = models.FloatField(
        blank=True,
        null=True,
        help_text="Confidence score for the annotation (0-1)"
    )
    
    is_ai_generated = models.BooleanField(
        default=False,
        help_text="Whether this annotation was generated by AI"
    )
    
    is_verified = models.BooleanField(
        default=False,
        help_text="Whether this annotation has been verified by a radiologist"
    )
    
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Date and time when the annotation was created"
    )
    
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text="Date and time of last update"
    )
    
    class Meta:
        db_table = "annotations"
        ordering = ["-created_at"]
        verbose_name = "Annotation"
        verbose_name_plural = "Annotations"
        indexes = [
            models.Index(fields=["dicom_file", "-created_at"]),
            models.Index(fields=["user", "-created_at"]),
            models.Index(fields=["label"]),
        ]
    
    def __str__(self):
        return f"{self.label} on {self.dicom_file.original_filename} by {self.user.username}"
    
    @property
    def coordinates_dict(self):
        """Return coordinates as a dictionary"""
        if isinstance(self.coordinates, dict):
            return self.coordinates
        return {}


class AnnotationHistory(models.Model):
    """Model for tracking annotation history/versions"""
    
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    
    annotation = models.ForeignKey(
        Annotation,
        on_delete=models.CASCADE,
        related_name='history',
        help_text="The annotation this history belongs to"
    )
    
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        help_text="User who made this change"
    )
    
    action = models.CharField(
        max_length=20,
        choices=(
            ("created", "Created"),
            ("updated", "Updated"),
            ("deleted", "Deleted"),
            ("verified", "Verified"),
        ),
        help_text="Action performed"
    )
    
    old_data = models.JSONField(
        blank=True,
        null=True,
        help_text="Previous state of the annotation"
    )
    
    new_data = models.JSONField(
        blank=True,
        null=True,
        help_text="New state of the annotation"
    )
    
    timestamp = models.DateTimeField(
        auto_now_add=True,
        help_text="When this action occurred"
    )
    
    class Meta:
        db_table = "annotation_history"
        ordering = ["-timestamp"]
        verbose_name = "Annotation History"
        verbose_name_plural = "Annotation Histories"
    
    def __str__(self):
        return f"{self.action} on {self.annotation.label} at {self.timestamp}"
