# Generated by Django 5.0.1 on 2025-11-07 18:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dicom_manager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        choices=[
                            ("rectangle", "Rectangle/Bounding Box"),
                            ("ellipse", "Ellipse"),
                            ("polygon", "Polygon"),
                            ("line", "Line"),
                            ("point", "Point"),
                            ("freehand", "Freehand"),
                        ],
                        default="rectangle",
                        help_text="Type of annotation tool used",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Label/description for the annotation (e.g., 'fracture', 'tumor')",
                        max_length=100,
                    ),
                ),
                (
                    "coordinates",
                    models.JSONField(
                        help_text="Coordinates of the annotation (format depends on annotation_type)"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#FF0000",
                        help_text="Color of the annotation in hex format",
                        max_length=7,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or comments about the annotation",
                        null=True,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="Confidence score for the annotation (0-1)",
                        null=True,
                    ),
                ),
                (
                    "is_ai_generated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this annotation was generated by AI",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this annotation has been verified by a radiologist",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the annotation was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Date and time of last update"
                    ),
                ),
                (
                    "dicom_file",
                    models.ForeignKey(
                        help_text="DICOM file this annotation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="dicom_manager.dicomfile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this annotation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Annotation",
                "verbose_name_plural": "Annotations",
                "db_table": "annotations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnotationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("verified", "Verified"),
                        ],
                        help_text="Action performed",
                        max_length=20,
                    ),
                ),
                (
                    "old_data",
                    models.JSONField(
                        blank=True,
                        help_text="Previous state of the annotation",
                        null=True,
                    ),
                ),
                (
                    "new_data",
                    models.JSONField(
                        blank=True, help_text="New state of the annotation", null=True
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this action occurred"
                    ),
                ),
                (
                    "annotation",
                    models.ForeignKey(
                        help_text="The annotation this history belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="annotations.annotation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who made this change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Annotation History",
                "verbose_name_plural": "Annotation Histories",
                "db_table": "annotation_history",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                fields=["dicom_file", "-created_at"],
                name="annotations_dicom_f_6414a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                fields=["user", "-created_at"], name="annotations_user_id_87524c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(fields=["label"], name="annotations_label_5c0cb1_idx"),
        ),
    ]
