# Generated by Django 5.0.1 on 2025-11-07 18:48

import dicom_manager.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DicomFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="DICOM file",
                        upload_to=dicom_manager.models.dicom_upload_path,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename of the uploaded file",
                        max_length=255,
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="DICOM metadata extracted from the file",
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(
                        blank=True,
                        help_text="Patient ID from DICOM metadata",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "study_date",
                    models.DateField(
                        blank=True,
                        help_text="Study date from DICOM metadata",
                        null=True,
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        blank=True,
                        help_text="Imaging modality (e.g., CR, DX)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "body_part",
                    models.CharField(
                        blank=True,
                        help_text="Body part examined",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the file was uploaded",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Date and time of last update"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether DICOM metadata has been extracted",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who uploaded this DICOM file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dicom_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DICOM File",
                "verbose_name_plural": "DICOM Files",
                "db_table": "dicom_files",
                "ordering": ["-upload_date"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-upload_date"],
                        name="dicom_files_owner_i_2b138a_idx",
                    ),
                    models.Index(
                        fields=["patient_id"], name="dicom_files_patient_95e767_idx"
                    ),
                    models.Index(
                        fields=["study_date"], name="dicom_files_study_d_b29b89_idx"
                    ),
                ],
            },
        ),
    ]
